/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { AccessControlEnumerableContract } from "./AccessControlEnumerable";
import { CerbyBotDetectionContract } from "./CerbyBotDetection";
import { CerbyCronJobsExecutionContract } from "./CerbyCronJobsExecution";
import { CerbySwapLP1155V1Contract } from "./CerbySwapLP1155V1";
import { CerbySwapV1Contract } from "./CerbySwapV1";
import { ERC1155Contract } from "./ERC1155";
import { ERC1155HolderContract } from "./ERC1155Holder";
import { ERC1155ReceiverContract } from "./ERC1155Receiver";
import { ERC1155SupplyContract } from "./ERC1155Supply";
import { ERC165Contract } from "./ERC165";
import { ERC20Contract } from "./ERC20";
import { IAccessControlContract } from "./IAccessControl";
import { IAccessControlEnumerableContract } from "./IAccessControlEnumerable";
import { ICerbyBotDetectionContract } from "./ICerbyBotDetection";
import { ICerbyCronJobsContract } from "./ICerbyCronJobs";
import { ICerbySwapLP1155V1Contract } from "./ICerbySwapLP1155V1";
import { ICerbyTokenContract } from "./ICerbyToken";
import { ICerbyTokenMinterBurnerContract } from "./ICerbyTokenMinterBurner";
import { IERC1155Contract } from "./IERC1155";
import { IERC1155MetadataURIContract } from "./IERC1155MetadataURI";
import { IERC1155ReceiverContract } from "./IERC1155Receiver";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IWethContract } from "./IWeth";
import { MigrationsContract } from "./Migrations";
import { TestCerUsdTokenContract } from "./TestCerUsdToken";
import { TestCerbyTokenContract } from "./TestCerbyToken";
import { TestUsdcTokenContract } from "./TestUsdcToken";
import { WETH9Contract } from "./WETH9";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "AccessControlEnumerable"): AccessControlEnumerableContract;
      require(name: "CerbyBotDetection"): CerbyBotDetectionContract;
      require(name: "CerbyCronJobsExecution"): CerbyCronJobsExecutionContract;
      require(name: "CerbySwapLP1155V1"): CerbySwapLP1155V1Contract;
      require(name: "CerbySwapV1"): CerbySwapV1Contract;
      require(name: "ERC1155"): ERC1155Contract;
      require(name: "ERC1155Holder"): ERC1155HolderContract;
      require(name: "ERC1155Receiver"): ERC1155ReceiverContract;
      require(name: "ERC1155Supply"): ERC1155SupplyContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "IAccessControl"): IAccessControlContract;
      require(
        name: "IAccessControlEnumerable"
      ): IAccessControlEnumerableContract;
      require(name: "ICerbyBotDetection"): ICerbyBotDetectionContract;
      require(name: "ICerbyCronJobs"): ICerbyCronJobsContract;
      require(name: "ICerbySwapLP1155V1"): ICerbySwapLP1155V1Contract;
      require(name: "ICerbyToken"): ICerbyTokenContract;
      require(name: "ICerbyTokenMinterBurner"): ICerbyTokenMinterBurnerContract;
      require(name: "IERC1155"): IERC1155Contract;
      require(name: "IERC1155MetadataURI"): IERC1155MetadataURIContract;
      require(name: "IERC1155Receiver"): IERC1155ReceiverContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IWeth"): IWethContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "TestCerUsdToken"): TestCerUsdTokenContract;
      require(name: "TestCerbyToken"): TestCerbyTokenContract;
      require(name: "TestUsdcToken"): TestUsdcTokenContract;
      require(name: "WETH9"): WETH9Contract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export {
  AccessControlEnumerableContract,
  AccessControlEnumerableInstance,
} from "./AccessControlEnumerable";
export {
  CerbyBotDetectionContract,
  CerbyBotDetectionInstance,
} from "./CerbyBotDetection";
export {
  CerbyCronJobsExecutionContract,
  CerbyCronJobsExecutionInstance,
} from "./CerbyCronJobsExecution";
export {
  CerbySwapLP1155V1Contract,
  CerbySwapLP1155V1Instance,
} from "./CerbySwapLP1155V1";
export { CerbySwapV1Contract, CerbySwapV1Instance } from "./CerbySwapV1";
export { ERC1155Contract, ERC1155Instance } from "./ERC1155";
export { ERC1155HolderContract, ERC1155HolderInstance } from "./ERC1155Holder";
export {
  ERC1155ReceiverContract,
  ERC1155ReceiverInstance,
} from "./ERC1155Receiver";
export { ERC1155SupplyContract, ERC1155SupplyInstance } from "./ERC1155Supply";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export {
  IAccessControlContract,
  IAccessControlInstance,
} from "./IAccessControl";
export {
  IAccessControlEnumerableContract,
  IAccessControlEnumerableInstance,
} from "./IAccessControlEnumerable";
export {
  ICerbyBotDetectionContract,
  ICerbyBotDetectionInstance,
} from "./ICerbyBotDetection";
export {
  ICerbyCronJobsContract,
  ICerbyCronJobsInstance,
} from "./ICerbyCronJobs";
export {
  ICerbySwapLP1155V1Contract,
  ICerbySwapLP1155V1Instance,
} from "./ICerbySwapLP1155V1";
export { ICerbyTokenContract, ICerbyTokenInstance } from "./ICerbyToken";
export {
  ICerbyTokenMinterBurnerContract,
  ICerbyTokenMinterBurnerInstance,
} from "./ICerbyTokenMinterBurner";
export { IERC1155Contract, IERC1155Instance } from "./IERC1155";
export {
  IERC1155MetadataURIContract,
  IERC1155MetadataURIInstance,
} from "./IERC1155MetadataURI";
export {
  IERC1155ReceiverContract,
  IERC1155ReceiverInstance,
} from "./IERC1155Receiver";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IWethContract, IWethInstance } from "./IWeth";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  TestCerUsdTokenContract,
  TestCerUsdTokenInstance,
} from "./TestCerUsdToken";
export {
  TestCerbyTokenContract,
  TestCerbyTokenInstance,
} from "./TestCerbyToken";
export { TestUsdcTokenContract, TestUsdcTokenInstance } from "./TestUsdcToken";
export { WETH9Contract, WETH9Instance } from "./WETH9";
